global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "snmp"
    metrics_path: /snmp
    params:
      module: [mikrotik]
    static_configs:
      - targets:
          - "172.11.0.1:161"  # SNMP Device 1 Cisco-router
          - "10.11.10.2:161"   # SNMP Device 1 Mikrotik-Router
          - "10.11.10.3:161"   # SNMP Device 2 Mikrotik-Router
          - "10.11.10.4:161" # SNMP Device 1 Switch cisco

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "172.20.255.250:9116"  # IP dan port dari SNMP exporter

  - job_name: "node_exporter"
    static_configs:
      - targets:
          - "node_exporter:9100"  # Menggunakan nama layanan Docker

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["172.20.255.250:8081"]
